services:
  api:
    build: .
    container_name: processor-api
    ports:
      - "9999:9999"
    expose:
      - 9999
    environment:
      - NODE_ENV=development
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=processor-redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=processor-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./src:/app/src
      - ./data/:/app/data/
    command: npx nodemon src/server.js
    networks:
      - backend
      - payment-processor
    links:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "100MB"

  postgres: 
    image: postgres:17-alpine
    container_name: processor-postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    networks:
      - backend
      - payment-processor
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  redis:
    image: "redis:7.0-alpine"
    container_name: processor-redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "85MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true